In [141]:
import numpy as np
import copy
import time
import random
import math
class Node:
    def __init__(self, turn, father, jogada, matriz, wins=0, ite=0):
        self.wins = wins
        self.ite = ite
        self.matriz = matriz
        self.turn = turn
        self.father = father
        self.jogada = jogada

This class represents a node for the search tree used in the MonteCarlo tree search. It saves the turn, the play, the matrix, the wins, the iteractions and the node father of the node.

In [142]:

class TicTacToe:
    WINDOW_LENGTH = 4
    def __init__ (self, matriz = np.zeros((6, 7)), game_over = False, turn = 3, row_quant = 6, col_quant = 7, linha = 0):
        self.matriz = matriz
        self.game_over = game_over
        self.turn = turn
        self.row_quant = row_quant
        self.col_quant = col_quant

This first lines of code are the bases for our functions and project since it defines most of the parameter we use and it defines our board in terms of size.

In [143]:
    def play (self):
        while self.turn != 0 and self.turn != 1:
            self.turn = int(input("Quem é que começa o jogo? Player1(0) ou Player2(1)? "))
        print(self.matriz)
        self.jogo()
        self.game_over = False

The function "play" is the function that asks who is playing first between the both players, and after getting the input of the player it prints the board.

In [144]:
    def jogada_valida (self, matriz, col):
        if col >= 0 and col < 7: #Pode se remover isto quando for com interface isto so é preciso com inputs
            if (self.matriz [5][col] == 0):
                return True
        return False

With this function we are capable of filtrer the input of the player so that the player only inputs number in between the values of the columns of the matrix and also verifies if it is possible to play on that position.

In [145]:
    def open_row (self, matriz, coluna):
        i = 0
        while not matriz [i][coluna] == 0:
            i+=1
        return i

This function it is reponsible for checking what line is not occupied so that your piece falls on the intended place.

In [146]:
    def drop_piece (self, matriz, row, coluna, player):
        matriz [row][coluna] = player

The funtion "drop_piece" is the function responsible for the position of the piece after the input.

In [147]:
    def winning_moves (self, board, piece):
        #Vertical
        for i in range (self.col_quant -3):
            for j in range (self.row_quant):
                if board [j][i] == piece and board [j][i+1] == piece and board [j][i+2] == piece and board [j][i+3] == piece:
                    return True

        #horizontal        
        for i in range (self.col_quant):
            for j in range (self.row_quant -3):
                if board [j][i] == piece and board [j+1][i] == piece and board [j+2][i] == piece and board [j+3][i] == piece:
                    return True
    
    
        #diagonal positiva
        for i in range (self.col_quant -3):
            for j in range (self.row_quant -3):
                if board [j][i] == piece and board [j+1][i+1] == piece and board [j+2][i+2] == piece and board [j+3][i+3] == piece:
                    return True 
    
        #diagonal negativa
        for i in range (self.col_quant -3):
            for j in range (3,self.row_quant):
                if board [j][i] == piece and board [j-1][i+1] == piece and board [j-2][i+2] == piece and board [j-3][i+3] == piece:
                    return True

The "winning_moves" function is responsible for checking if the winning condition of 4 pieces of the same type are connected on a row, collumn or even on a diagonal. 

In [ ]:
    def jogo (self):
        while not self.game_over:
            if self.turn == 0:
                self.turn += 1
                self.turn = self.turn % 2
                jogada = int(input("Em que coluna quer colocar a peça? (1-7)? "))
                if self.jogada_valida (self.matriz, jogada-1): #Jogada -1 só é preciso pq temos input e fica mais intuitivo, com interface probably n e preciso
                    row = self.open_row (self.matriz, jogada-1)
                    self.drop_piece ( self.matriz, row, jogada-1, 1)
                    print (np.flip (self.matriz, 0))
                    if self.winning_moves (self.matriz, 1):
                        print ("Passou, passou, passou um avião e tinha lá escrito player 1 é campeão ")
                        self.game_over = True;
                        break
                else:
                    print ("Jogada invalida")
                    self.turn = 0
            
            if self.turn == 1:
                self.turn += 1
                self.turn = self.turn % 2
                jogada = self.AAAAporra()
                if self.jogada_valida (self.matriz, jogada):
                    row = self.open_row (self.matriz, jogada)
                    self.drop_piece ( self.matriz, row, jogada, 2)
                    print (np.flip (self.matriz, 0)) 
                    if self.winning_moves (self.matriz, 2):
                        print ("És mesmo bom tu, reizao, os teus pais devem gostar mesmo de ti, ao contrario do player 1")
                        self.game_over = True
                else:
                    print ("Jogada invalida")
                    self.turn = 1

            draw = True

            for i in range (6):
                if self.matriz [5][i] == 0:
                    draw = False
                    break

            if draw == True:
                self.game_over == True
                print ("Burros!")

The "jogo" function is the function responsible for the printing of the messages after a winning condition is met or even a Draw, being that every message is different for the Player1, Player2 and Draw. It also is reponsible for asking the player where it wants to play and if that play is not possible it prints a message saying is a invalid option and asks once more about where it wants to play.

In [149]:
    def score_position(self, board, piece):
            score = 0

            centre_array = [int(i) for i in list(board[:, self.col_quant // 2])]
            centre_count = centre_array.count(piece)
            score += centre_count * 3


            for r in range(self.row_quant):
                row_array = [int(i) for i in list(board[r, :])]
                for c in range(self.col_quant - 3):

                    window = row_array[c:c + 4]
                    score += self.evaluate_window(window, piece)


            for c in range(self.col_quant):
                col_array = [int(i) for i in list(board[:, c])]
                for r in range(self.row_quant - 3):
    
                    window = col_array[r:r + 4]
                    score += self.evaluate_window(window, piece)


            for r in range(self.row_quant - 3):
                for c in range(self.col_quant - 3):
    
                    window = [board[r + i][c + i] for i in range(4)]
                    score += self.evaluate_window(window, piece)


            for r in range(self.row_quant - 3):
                for c in range(self.col_quant - 3):

                    window = [board[r + 3 - i][c + i] for i in range(4)]
                    score += self.evaluate_window(window, piece)

            return score

This function verifies all the possible plays (diagonals, verticals and horizontals) and it creates a smaller array composed of 4 elements that will be evaluated in the function "evaluate_window" returning then the score. 

In [150]:
    def evaluate_window(self, window, piece):
            score = 0
            opp_piece = 1
            piece = 2

            if window.count(piece) == 4:
                score += 100
            elif window.count(piece) == 3 and window.count(0) == 1:
                score += 5

            elif window.count(piece) == 2 and window.count(0) == 2:
                score += 2

            if window.count(opp_piece) == 3 and window.count(0) == 1:
                score -= 4

            return score

This function is the heuristhic of the AStar(A*), where it evaluates which pieces are inside of an array of 4 elements of the board.

In [151]:
    def AAestrelita(self): #função do A*(AStar)
            best_score = 0 
            best_move = 4
            
            for col in range (self.col_quant):
                board_depp = self.matriz.copy()
                if self.jogada_valida(board_depp, col):
                    row = self.open_row(board_depp, col)
                    self.drop_piece(board_depp, row,col, 2)
                    score = self.score_position(board_depp, 2)
                    if score >= best_score:
                        best_score = score
                        best_move = col

            return best_move

The function "AAestrelita" creates a copy of the board with a new piece and then evaluates the simulated board with the function "score_position". It does this for every possible play, returning the best move for the given position.

In [152]:
    def jogo_simulado (self, game_over, node_father):
            turn = node_father.turn
            matriz_copy = node_father.matriz
            while not game_over:
                matriz_copy = copy.deepcopy(node_father.matriz)
                if turn == 0:
                    turn += 1
                    jogada = random.randint(1, 7)
                    if self.jogada_valida (matriz_copy, jogada-1): #Jogada -1 soé preciso pq temos input e fica mais intuitivo, com interface probably n e preciso
                        row = self.open_row (matriz_copy, jogada-1)
                        self.drop_piece (matriz_copy, row, jogada-1, 1)
                        node_son = self.existing_node (matriz_copy)
                        if node_son != False:
                            node_father = node_son
                        if node_son == False:
                            node_son = Node(turn, node_father, jogada, matriz_copy)
                            self.search_tree.append (node_son)
                            node_father = node_son
                        if self.winning_moves (matriz_copy, 1):
                            self.backpropagation(node_son, 0)
                            game_over = True
                    else:
                        turn = 0
                
                else:
                    turn -= 1
                    jogada = random.randint(1, 7)
                    if self.jogada_valida (matriz_copy, jogada-1):
                        row = self.open_row (matriz_copy, jogada-1)
                        self.drop_piece (matriz_copy, row, jogada-1, 2)
                        node_son = self.existing_node (matriz_copy)
                        if node_son != False:
                            node_father = node_son
                        if node_son == False:
                            node_son = Node(turn, node_father, jogada, matriz_copy)
                            self.search_tree.append(node_son)
                            node_father = node_son
                        if self.winning_moves (matriz_copy, 2):
                            self.backpropagation(node_son, 1)
                            game_over = True
                    else:
                        turn = 1

                draw = True
                for i in range (6):
                    if self.matriz [5][i] == 0:
                        draw = False
                        break
                if draw == True:
                    game_over == True

This function simulates a game, starting from the node choosen in the MCTS function. It plays using random plays for both players until there is a winner. After every play, it evaluates if the node already exists, and if it doesn't it creates a new node and adds it to the search tree. When the game is over it calls the backpropagation function that updates the iteractions and the wins (if thatś the case), from the leaf node until the root.

In [153]:
    def MCTS (self):
            matriz = copy.deepcopy(self.matriz)
            first_node = self.existing_node (matriz)
            if first_node == False:
                first_node = Node (self.turn, None, None, matriz)
                self.search_tree.append(first_node)
            for i in range (100):
                self.jogo_simulado(False, first_node)
            start_time = time.time()
            while time.time() - start_time < 7:
                best_node = self.search_node()
                self.jogo_simulado(False, best_node)
            best_score = 0
            best_move = 4
            for i in range (len(self.search_tree)):
                if self.search_tree[i].father == first_node:
                    score = self.search_tree[i].wins/self.search_tree[i].ite
                    print(score)
                    if score > best_score:
                        best_score = score
                        best_move = self.search_tree[i].jogada
            return best_move

This "MCTS" function starts by evaluating if the current state of the game already has a node representing it. If not, it creates one. Then it runs 100 times the simulated game from the first node, just to "get the search tree going". After that, it chooses the best node to expand and simulates a game from that node x times while the time is under 7 seconds. In the end, it evaluates all the children from the current state of the game and chooses the best play, using a score of wins/iteractions for each children.

In [154]:
    def existing_node (self, matriz):
            for i in range (len(self.search_tree)):
                if np.array_equal(self.search_tree[i].matriz, matriz):
                    return self.search_tree[i]
            return False

This function evaluates if a node already exists in the search tree, comparing the matrix given with every matrix in the search tree. If there is, it returns the reference for the existing node, if not it returns False.

In [155]:
    def backpropagation (self, first_node, win):
            if win == 0:
                node = first_node
                while node != None:
                    node.ite += 1
                    node = node.father
            if win == 1:
                node = first_node
                while node != None:
                    node.ite += 1
                    node.wins += 1
                    node = node.father

This function does the backpropagation of iteractions and wins (if the case) from the leaf node (first_node) until the root.

In [156]:
    def search_node (self):
            best_score = 0
            best_node = None
            for i in range (len(self.search_tree)):
                score = 0
                node = self.search_tree [i]
                if (node.father == None):
                    if (node.ite == 0):
                        score = 2
                    else:
                        score = node.wins/node.ite
                else:
                    if (node.ite == 0):
                        score = 2
                    else:
                        score = node.wins/node.ite + math.sqrt(2)*math.sqrt(2*(math.log(node.father.ite)/node.ite))
                if (score >= best_score):
                    best_score = score
                    best_node = node
            return best_node

This function is used to decide which is the best node to expand next in the MCTS. It evaluates the score of each node in the search tree using the proper algorithm and in the end it returns the reference to the most insteresting node to expand.

In [5]:
import numpy as np
import copy
import time
import random
import math

class Node:
    def __init__(self, turn, father, jogada, matriz, wins=0, ite=0):
        self.wins = wins
        self.ite = ite
        self.matriz = matriz
        self.turn = turn
        self.father = father
        self.jogada = jogada
    
class TicTacToe:
    def __init__ (self, matriz = np.zeros((6, 7)), game_over = False, turn = 3, row_quant = 6, col_quant = 7, linha = 0, search_tree = []):
        self.matriz = matriz
        self.game_over = game_over
        self.turn = turn
        self.row_quant = row_quant
        self.col_quant = col_quant
        self.search_tree = search_tree
        
    def play (self):
        while self.turn != 0 and self.turn != 1:
            self.turn = int(input("Quem é que começa o jogo? MCTS(0) ou A*(1)? "))
        print(self.matriz)
        self.jogo()
        self.game_over = False

    def jogada_valida (self, matriz, col):
        if col >= 0 and col < 7: #Pode se remover isto quando for com interface isto so é preciso com inputs
            if (self.matriz [5][col] == 0):
                return True
        return False

    def jogo (self):
        while not self.game_over:
            if self.turn == 0:
                self.turn += 1
                self.turn = self.turn % 2
                jogada = self.MCTS()
                if self.jogada_valida (self.matriz, jogada-1): #Jogada -1 soé preciso pq temos input e fica mais intuitivo, com interface probably n e preciso
                    row = self.open_row (self.matriz, jogada-1)
                    self.drop_piece (self.matriz, row, jogada-1, 1)
                    print (np.flip(self.matriz, 0))
                    if self.winning_moves (self.matriz, 1):
                        print ("És mesma bom tu MCTS, reizao, os teus pais devem gostar mesmo de ti, ao contrario do A*")
                        self.game_over = True
                else:
                    print ("Jogada invalida")
                    self.turn = 0
            
            if self.turn == 1:
                self.turn += 1
                self.turn = self.turn % 2
                jogada = self.AAestrelita()
                if self.jogada_valida (self.matriz, jogada):
                    row = self.open_row (self.matriz, jogada)
                    self.drop_piece (self.matriz, row, jogada, 2)
                    print (np.flip (self.matriz, 0)) 
                    if self.winning_moves (self.matriz, 2):
                        print ("És mesma bom tu A*, reizao, os teus pais devem gostar mesmo de ti, ao contrario do MCTS")
                        self.game_over = True
                else:
                    print ("Jogada invalida")
                    self.turn = 1

            draw = True

            for i in range (6):
                if self.matriz [5][i] == 0:
                    draw = False
                    break

            if draw == True:
                self.game_over == True
                print ("Burros!")
            
    def open_row (self, matriz, coluna):
        i = 0
        while (i < self.col_quant-1) and (matriz [i][coluna] != 0): 
            i+=1
        return i
    
    def drop_piece (self, matriz, row, coluna, player):
        if (row < self.row_quant):
            matriz [row][coluna] = player

    
    #Em vez de fazer tudo separado, simplesmente criar def winning moves 
    def winning_moves (self, matriz, piece):
        #Vertical
        for i in range (self.col_quant -3):
            for j in range (self.row_quant):
                if matriz [j][i] == piece and matriz [j][i+1] == piece and matriz [j][i+2] == piece and matriz [j][i+3] == piece:
                    return True

        #horizontal        
        for i in range (self.col_quant):
            for j in range (self.row_quant -3):
                if matriz [j][i] == piece and matriz [j+1][i] == piece and matriz [j+2][i] == piece and matriz [j+3][i] == piece:
                    return True
    
    
        #diagonal positiva
        for i in range (self.col_quant -3):
            for j in range (self.row_quant -3):
                if matriz [j][i] == piece and matriz [j+1][i+1] == piece and matriz [j+2][i+2] == piece and matriz [j+3][i+3] == piece:
                    return True 
    
        #diagonal negativa
        for i in range (self.col_quant -3):
            for j in range (3,self.row_quant):
                if matriz [j][i] == piece and matriz [j-1][i+1] == piece and matriz [j-2][i+2] == piece and matriz [j-3][i+3] == piece:
                    return True

    def score_position(self, board, piece):
        score = 0

        centre_array = [int(i) for i in list(board[:, self.col_quant // 2])]
        centre_count = centre_array.count(piece)
        score += centre_count * 3


        for r in range(self.row_quant):
            row_array = [int(i) for i in list(board[r, :])]
            for c in range(self.col_quant - 3):

                window = row_array[c:c + 4]
                score += self.evaluate_window(window, piece)


        for c in range(self.col_quant):
            col_array = [int(i) for i in list(board[:, c])]
            for r in range(self.row_quant - 3):
 
                window = col_array[r:r + 4]
                score += self.evaluate_window(window, piece)


        for r in range(self.row_quant - 3):
            for c in range(self.col_quant - 3):
 
                window = [board[r + i][c + i] for i in range(4)]
                score += self.evaluate_window(window, piece)


        for r in range(self.row_quant - 3):
            for c in range(self.col_quant - 3):

                window = [board[r + 3 - i][c + i] for i in range(4)]
                score += self.evaluate_window(window, piece)

        return score


    def evaluate_window(self, window, piece):
        score = 0
        opp_piece = 1
        piece = 2

        if window.count(piece) == 4:
            score += 100
        elif window.count(piece) == 3 and window.count(0) == 1:
            score += 5

        elif window.count(piece) == 2 and window.count(0) == 2:
            score += 2


        return score
    
    def AAestrelita(self):
        best_score = 0 
        best_move = 4
        
        for col in range (self.col_quant):
            board_depp = self.matriz.copy()
            if self.jogada_valida(board_depp, col):
                row = self.open_row(board_depp, col)
                self.drop_piece(board_depp, row,col, 2)
                score = self.score_position(board_depp, 2)
                if score >= best_score:
                    best_score = score
                    best_move = col

        return best_move

    

# This function simulates a game, starting from the node choosen in the MCTS function. It plays using random plays for both players until there is a winner. After every play, it evaluates if the node already exists, and if it doesn't it creates a new node and adds it to the search tree. When the game is over it calls the backpropagation function that updates the iteractions and the wins (if thatś the case), from the leaf node until the root.
    def jogo_simulado (self, game_over, node_father):
        turn = node_father.turn
        matriz_copy = node_father.matriz
        while not game_over:
            matriz_copy = copy.deepcopy(node_father.matriz)
            if turn == 0:
                turn += 1
                jogada = random.randint(1, 7)
                if self.jogada_valida (matriz_copy, jogada-1): #Jogada -1 soé preciso pq temos input e fica mais intuitivo, com interface probably n e preciso
                    row = self.open_row (matriz_copy, jogada-1)
                    self.drop_piece (matriz_copy, row, jogada-1, 1)
                    node_son = self.existing_node (matriz_copy)
                    if node_son != False:
                        node_father = node_son
                    if node_son == False:
                        node_son = Node(turn, node_father, jogada, matriz_copy)
                        self.search_tree.append (node_son)
                        node_father = node_son
                    if self.winning_moves (matriz_copy, 1):
                        self.backpropagation(node_son, 1)
                        game_over = True
                else:
                    turn = 0
            
            else:
                turn -= 1
                jogada = random.randint(1, 7)
                if self.jogada_valida (matriz_copy, jogada-1):
                    row = self.open_row (matriz_copy, jogada-1)
                    self.drop_piece (matriz_copy, row, jogada-1, 2)
                    node_son = self.existing_node (matriz_copy)
                    if node_son != False:
                        node_father = node_son
                    if node_son == False:
                        node_son = Node(turn, node_father, jogada, matriz_copy)
                        self.search_tree.append(node_son)
                        node_father = node_son
                    if self.winning_moves (matriz_copy, 2):
                        self.backpropagation(node_son, 0)
                        game_over = True
                else:
                    turn = 1

            draw = True
            for i in range (6):
                if self.matriz [5][i] == 0:
                    draw = False
                    break
            if draw == True:
                game_over == True
#This MCTS function starts by evaluating if the current state of the game already has a node representing it. If not, it creates one. Then it runs 100 times the simulated game from the first node, just to "get the search tree going". After that, it chooses the best node to expand and simulates a game from that node x times while the time is under 7 seconds. In the end, it evaluates all the children from the current state of the game and chooses the best play, using a score of wins/iteractions for each children.
    def MCTS (self):
        matriz = copy.deepcopy(self.matriz)
        first_node = self.existing_node (matriz)
        if first_node == False:
            first_node = Node (self.turn, None, None, matriz)
            self.search_tree.append(first_node)
        for i in range (100):
            self.jogo_simulado(False, first_node)
        start_time = time.time()
        while time.time() - start_time < 7:
            best_node = self.search_node()
            self.jogo_simulado(False, best_node)
        best_score = 0
        best_move = 4
        for i in range (len(self.search_tree)):
            if self.search_tree[i].father == first_node:
                score = self.search_tree[i].wins/self.search_tree[i].ite
                if score > best_score:
                    best_score = score
                    best_move = self.search_tree[i].jogada
        return best_move

#This function evaluates if a node already exists in the search tree, comparing the matrix given with every matrix in the search tree. If there is, it returns the reference for the existing node, if not it returns False.
    def existing_node (self, matriz):
        for i in range (len(self.search_tree)):
            if np.array_equal(self.search_tree[i].matriz, matriz):
                return self.search_tree[i]
        return False

#This function does the backpropagation of iteractions and wins (if the case) from the leaf node (first_node) until the root.
    def backpropagation (self, first_node, win):
        if win == 0:
            node = first_node
            while node != None:
                node.ite += 1
                node = node.father
        if win == 1:
            node = first_node
            while node != None:
                node.ite += 1
                node.wins += 1
                node = node.father
#This function is used to decide which is the best node to expand next in the MCTS. It evaluates the score of each node in the search tree using the proper algorithm and in the end it returns the reference to the most insteresting node to expand.
    def search_node (self):
        best_score = 0
        best_node = None
        for i in range (len(self.search_tree)):
            score = 0
            node = self.search_tree [i]
            if (node.father == None):
                if (node.ite == 0):
                    score = 2
                else:
                    score = node.wins/node.ite
            else:
                if (node.ite == 0):
                    score = 2
                else:
                    score = node.wins/node.ite + math.sqrt(2)*math.sqrt(2*(math.log(node.father.ite)/node.ite))
            if (score >= best_score):
                best_score = score
                best_node = node
        return best_node
game = TicTacToe()
game.play()



[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]


KeyboardInterrupt: 